survey_analytics/analysis/urls.py
from django.urls import path

from . import views

app_name = 'analysis'

urlpatterns = [
    path('analysisSurveys/', views.analysisSurveys, name='analysisSurveys'),
    path('lastSurveys/', views.lastSurveys, name='lastSurveys'),
    path('graphs/<int:survey_id>/', views.analysisGraphs, name='analysis_graphs'),
    path('download_pdf/<int:survey_id>/', views.downloadPDF, name='download_pdf'),
    path('delete_survey/<int:survey_id>/', views.deleteSurvey, name='delete_survey'),
]

survey_analytics/survey_analytics/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

handler404 = 'errors.views.handler404'
handler401 = 'errors.views.handler401'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('analysis.urls')),
    path('',include('users.urls')),
    path('',include('errors.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

survey_analytics/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('logout/', views.logout, name='logout'),
    path('forgot-password/', views.PasswordResetView.as_view(), name='password_reset'),
    path('forgot-password/password-reset-done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('change-password/', views.CustomPasswordChangeView.as_view(), name='change_password'),
]

survey_analytics/users/forms.py
# users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.utils.text import capfirst
from django.utils.translation import gettext_lazy as _

# Formulario para el registro de usuarios
class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-input',
            'id': 'password',
            'placeholder': 'Enter your password'
        }),
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-input',
                'placeholder': 'Enter your username'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-input',
                'placeholder': 'Enter your email'
            }),
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email is already in use.")
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        user.is_active = False
        if commit:
            user.save()
        return user


# Formulario para el inicio de sesión
class AuthenticationForm(forms.Form):
    username = forms.CharField(
        max_length=254,
        widget=forms.TextInput(attrs={
            'autofocus': True,
            'class': 'form-input',
            'placeholder': 'Enter your username'
        }),
    )
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={
            'class': 'form-input',
            'placeholder': 'Enter your password',
            'id': 'password',
        }),
    )

    error_messages = {
        'invalid_login': _(
            "Please enter a correct username and password. Note that both fields may be case-sensitive."
        ),
        'inactive': _("This account is inactive. Please activate it"),
    }

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user_cache = None
        super().__init__(*args, **kwargs)
        self.fields['username'].label = capfirst(self.fields['username'].label)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username is not None and password:
            self.user_cache = authenticate(self.request, username=username, password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'username': self.fields['username'].label},
                )
            else:
                self.confirm_login_allowed(self.user_cache)
        return self.cleaned_data

    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

    def get_user(self):
        return self.user_cache

survey_analytics/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout as auth_logout, login as auth_login
from .forms import UserRegisterForm, AuthenticationForm
from .decorators import anonymous_required
from django.utils.decorators import method_decorator
from django.core.mail import EmailMultiAlternatives
from django.conf import settings
from django.template.loader import render_to_string
from django.utils import timezone
from django.urls import reverse, reverse_lazy
from django.contrib.auth.tokens import default_token_generator
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.decorators import login_required

def index(request):
    title = "Homepage"
    return render(request, 'users/index.html', {'title': title})

@anonymous_required(redirect_url='errors:error_400')
def login(request):
    title = "Login"
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            if 'remember_me' in request.POST:
                request.session.set_expiry(1209600)
            else:
                request.session.set_expiry(0)

            context = {
                'user': user,
                'login_datetime': timezone.now().strftime("%d/%m/%Y %H:%M:%S"),
                'device_info': request.META.get('HTTP_USER_AGENT', 'Unknown')
            }

            html_content = render_to_string('emails/login_email.html', context)
            subject = 'Alert: Someone recently logged in'
            from_email = settings.DEFAULT_FROM_EMAIL
            to_email = [user.email]

            msg = EmailMultiAlternatives(subject, '', from_email, to_email)
            msg.attach_alternative(html_content, "text/html")
            msg.send()

            return redirect('users:index')
    else:
        form = AuthenticationForm(request)

    return render(request, 'users/login.html', {'title': title, 'form': form})

@anonymous_required(redirect_url='errors:error_400')
def register(request):
    title = "Register"
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()

            token = default_token_generator.make_token(user)
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            activation_link = request.build_absolute_uri(
                reverse('users:activate', kwargs={'uidb64': uid, 'token': token})
            )

            context = {
                'user': user,
                'activation_link': activation_link,
                'register_datetime': timezone.now().strftime("%d/%m/%Y %H:%M:%S"),
            }

            html_content = render_to_string('emails/register_verification.html', context)
            subject = 'Welcome to our website - Activate your account'
            from_email = settings.DEFAULT_FROM_EMAIL
            to_email = [user.email]
            msg = EmailMultiAlternatives(subject, '', from_email, to_email)
            msg.attach_alternative(html_content, "text/html")
            msg.send()
            messages.info(request,
                          "We have sent you an email to activate your account. Please check your email and activate your account before logging in.")
            return redirect('users:login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'title': title, 'form': form})

def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        User = get_user_model()
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Your account has been successfully activated! You can now log in.')
        return redirect('users:login')
    else:
        messages.error(request, 'The activation link is invalid or has expired.')
        return redirect('users:login')

def logout(request):
    auth_logout(request)
    return redirect('users:index')

@method_decorator(anonymous_required(redirect_url='errors:error_400'), name='dispatch')
class PasswordResetView(auth_views.PasswordResetView):
    template_name = 'users/forgot_password.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    subject_template_name = 'users/password_reset_subject.txt'
    success_url = reverse_lazy('users:password_reset_done')

@method_decorator(anonymous_required(redirect_url='errors:error_400'), name='dispatch')
class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'users/password_reset_done.html'

@method_decorator(anonymous_required(redirect_url='errors:error_400'), name='dispatch')
class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        response = super().form_valid(form)
        auth_logout(self.request)
        messages.success(
            self.request,
            "Your password has been changed and your session has been ended. Please log in again with your new password."
        )
        return response

@method_decorator(login_required(login_url='errors:error_401'), name='dispatch')
class CustomPasswordChangeView(PasswordChangeView):

    template_name = 'users/password_change.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        response = super().form_valid(form)
        auth_logout(self.request)
        messages.success(
            self.request,
            "Your password has been changed successfully. Please log in again."
        )
        return response

survey_analytics/users/templates/users/forgot_password.html
{% extends '../layout/base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% load widget_tweaks %}
{% block content %}
<main class="login-container">
    <div class="login-card">
        <div class="login-image">
            <img src="{% static 'images/cat400.png' %}" alt="Error loading image" class="CatImage">
        </div>
        <div class="login-form">
            <div class="form-header">
                <img src="{% static 'images/icons/userIcon.svg' %}" alt="User icon" class="icons">
                <h1>Reset Your Password</h1>
                <p>Please enter your email address to reset your password.</p>
            </div>
            <form method="post" novalidate>
                {% csrf_token %}
                {{ form.email|add_class:"form-input"|attr:"placeholder:Enter your email" }}
                <button type="submit" class="btn-login">Submit</button>
            </form>
            <div class="form-footer">
                <p>Remember your password? <br> <a href="{% url 'users:login' %}">Log in</a></p>
            </div>
        </div>
    </div>
</main>
{% endblock %}

survey_analytics/users/templates/users/index.html
{% extends '../layout/base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}
{% block content %}
<section class="hero">
    <div class="hero-content">
        <h1 class="hero-title">&ensp; Transform your survey <br> data into actionable <br>insights</h1>
        <p class="hero-text">With SurveyAnalytics, streamline your survey analysis <br>process. Forget about complex tools.<br>
            Our platform simplifies everything, from data uploads to <br>detailed analysis. Gain insights that help you make better <br>decisions in real-time.</p>
        {% if user.is_authenticated %}
             <a href="{% url 'analysis:analysisSurveys' %}" class="btn-primary">Get Started ↗</a>
        {% else %}
            <a href="{% url 'users:login' %}" class="btn-primary">Get Started ↗</a>
        {% endif %}

    </div>
</section>
<img src="{% static 'images/catHomePage.png' %}" alt="Error while loading the image" id="hero-img">
{% endblock %}

survey_analytics/users/templates/users/login.html
{% extends '../layout/base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block extra_js %}
    <script>
        const eyeOpenIcon = "{% static 'images/icons/eyeOpenIcon.svg' %}";
        const eyeClosedIcon = "{% static 'images/icons/eyeClosedIcon.svg' %}";
    </script>
    <script src="{% static 'js/togglePasswordVisibility.js' %}"></script>
{% endblock %}
{% block content %}
<main class="login-container">
    <div class="login-card">
        <div class="login-image">
            <img src="{% static 'images/catLogin.png' %}" alt="Error while loading the image" class="CatImage">
        </div>
        <div class="login-form">
            <div class="form-header">
                <img src="{% static 'images/icons/userIcon.svg' %}" alt="Error while loading the image" class="icons">
                <h1>Welcome back!</h1>
                <p>Please enter your credentials</p>
            </div>

            {% if messages %}
              <div class="django-messages">
                {% for message in messages %}
                  <div class="message {{ message.tags }}">
                    {{ message }}
                  </div>
                {% endfor %}
              </div>
            {% endif %}

            <form method="post" novalidate>
                {% csrf_token %}
                {{ form.non_field_errors }}

                <div class="form-group">
                    {{ form.username }}
                    {% if form.username.errors %}
                        <div class="error">{{ form.username.errors }}</div>
                    {% endif %}
                </div>

                <div class="form-group">
                    <div class="password-container">
                        {{ form.password }}
                        <img src="{% static 'images/icons/eyeClosedIcon.svg' %}"
                             alt="Toggle password visibility"
                             id="toggle-password"
                             class="password-toggle"
                             onclick="togglePasswordVisibility()">
                    </div>
                    {% if form.password.errors %}
                        <div class="error">{{ form.password.errors }}</div>
                    {% endif %}
                </div>

                <div class="form-options">
                    <label>
                        <input type="checkbox" name="remember_me"> Remember me
                    </label>
                    <a href="{% url 'users:password_reset' %}" class="forgot-password">&ensp;&ensp;&ensp;Forgot your password?</a>
                </div>

                <button type="submit" class="btn-login">Log in</button>
            </form>
            <div class="form-footer">
                <p>Don't you have an account? <br> <a href="{% url 'users:register' %}">Create one</a></p>
            </div>
        </div>
    </div>
</main>
{% endblock %}

survey_analytics/users/templates/users/password_change.html
{% extends '../layout/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
<main class="login-container">
    <div class="login-card">
        <div class="login-form" style="width:100%;">
            <div class="form-header">
                <h1>Change Password</h1>
                <p>Enter your current password and your new password.</p>
            </div>

            {% if messages %}
                <div class="django-messages">
                    {% for message in messages %}
                        <div class="message {{ message.tags }}">
                            <p>{{ message }}</p>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}

            <form method="post" novalidate>
                {% csrf_token %}

                <div class="form-group password-container">
                    {{ form.old_password|add_class:"form-input"|attr:"placeholder:Enter your current password" }}
                    <img src="{% static 'images/icons/eyeClosedIcon.svg' %}" class="password-toggle" onclick="togglePassword('id_old_password')">
                </div>

                <div class="form-group password-container">
                    {{ form.new_password1|add_class:"form-input"|attr:"placeholder:Enter your new password" }}
                    <img src="{% static 'images/icons/eyeClosedIcon.svg' %}" class="password-toggle" onclick="togglePassword('id_new_password1')">
                </div>

                <div class="form-group password-container">
                    {{ form.new_password2|add_class:"form-input"|attr:"placeholder:Retype your new password" }}
                    <img src="{% static 'images/icons/eyeClosedIcon.svg' %}" class="password-toggle" onclick="togglePassword('id_new_password2')">
                </div>

                <button type="submit" class="btn-login">Change Password</button>
            </form>
        </div>
    </div>
</main>

<script>
    function togglePassword(fieldId) {
        var field = document.getElementById(fieldId);
        var eyeIcon = event.target;

        if (field.type === "password") {
            field.type = "text";
            eyeIcon.src = "{% static 'images/icons/eyeOpenIcon.svg' %}";
        } else {
            field.type = "password";
            eyeIcon.src = "{% static 'images/icons/eyeClosedIcon.svg' %}";
        }
    }
</script>
{% endblock %}

survey_analytics/users/templates/users/password_reset_complete.html
{% extends '../layout/base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block content %}
<main class="login-container">
    <div class="login-card">
        <div class="login-form" style="width:100%;">
            <div class="form-header">
                <h1>Password Reset Successful</h1>
                <p>Your password has been successfully changed. You can now log in with your new password.</p>
            </div>
            <div class="form-footer">
                <p>Return to <a href="{% url 'users:login' %}">Log in</a></p>
            </div>
        </div>
    </div>
</main>
{% endblock %}

survey_analytics/users/templates/users/password_reset_confirm.html
{% extends '../layout/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
<main class="login-container">
    <div class="login-card">
        <div class="login-form" style="width:100%;">
            <div class="form-header">
                <h1>Set New Password</h1>
                <p>Please enter your new password below.</p>
            </div>

            {% if messages %}
                <div class="django-messages">
                    {% for message in messages %}
                        <div class="message {{ message.tags }}">
                            <p>{{ message }}</p>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}

            <form method="post" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    {{ form.new_password1|add_class:"form-input"|attr:"placeholder:Enter your new password"  }}
                </div>
                <div class="form-group">
                    {{ form.new_password2|add_class:"form-input"|attr:"placeholder:Retype your new password"  }}
                </div>
                <button type="submit" class="btn-login">Change Password</button>
            </form>
        </div>
    </div>
</main>
{% endblock %}

survey_analytics/users/templates/users/password_reset_done.html
{% extends '../layout/base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block content %}
<main class="login-container">
    <div class="login-card">
        <div class="login-form" style="width:100%;">
            <div class="form-header">
                <h1>Email Sent</h1>
                <p>If an account exists with the email you entered, you will receive instructions on how to reset your password.</p>
            </div>
            <div class="form-footer">
                <p>Return to <a href="{% url 'users:login' %}">Log in</a></p>
            </div>
        </div>
    </div>
</main>
{% endblock %}

survey_analytics/users/templates/users/password_reset_email.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Restablecimiento de Contraseña</title>
  <style type="text/css">
    body {
      background-color: #f5f5f5;
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 20px;
    }
    .card {
      max-width: 600px;
      margin: 0 auto;
      background-color: #ffffff;
      border-radius: 8px;
      box-shadow: 0 2px 5px rgba(0,0,0,0.1);
      padding: 20px;
      color: #333;
    }
    .btn {
      background-color: #838383;
      color: #ffffff;
      padding: 10px 15px;
      text-decoration: none;
      border-radius: 5px;
    }
  </style>
</head>
<body>
  <div class="card">
    <h2>Hola, {{ user.get_username }}!</h2>
    <p>
      Se ha solicitado un restablecimiento de contraseña para tu cuenta.
      Si tú realizaste esta solicitud, haz clic en el siguiente enlace para restablecer tu contraseña:
    </p>
    <p style="text-align: center;">
      <a class="btn" href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">Restablecer Contraseña</a>
    </p>
    <p>
      Si no has solicitado este cambio, ignora este correo.
    </p>
  </div>
</body>
</html>

survey_analytics/users/templates/users/register.html
{% extends '../layout/base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block extra_js %}
    <script>
        const eyeOpenIcon = "{% static 'images/icons/eyeOpenIcon.svg' %}";
        const eyeClosedIcon = "{% static 'images/icons/eyeClosedIcon.svg' %}";
    </script>
    <script src="{% static 'js/togglePasswordVisibility.js' %}"></script>
{% endblock %}
{% block content %}
<main class="login-container">
    <div class="login-card">
        <div class="login-image">
            <img src="{% static 'images/catRegister.png' %}" alt="Error while loading the image" class="CatImage">
        </div>
        <div class="login-form">
            <div class="form-header">
                <img src="{% static 'images/icons/userIcon.svg' %}" alt="Error while loading the image" class="icons">
                <h1>Welcome here!</h1>
                <p>Please create your new account</p>
            </div>
            <form method="post">
                {% csrf_token %}

                <div class="form-group">
                    {{ form.username }}
                    {% if form.username.errors %}
                        <div class="error">{{ form.username.errors }}</div>
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.email }}
                    {% if form.email.errors %}
                        <div class="error">{{ form.email.errors }}</div>
                    {% endif %}
                </div>

                <div class="form-group">
                    <div class="password-container">
                        {{ form.password }}
                        <img src="{% static 'images/icons/eyeClosedIcon.svg' %}"
                             alt="Error while loading the image"
                             id="toggle-password"
                             class="password-toggle"
                             onclick="togglePasswordVisibility()">
                    </div>
                    {% if form.password.errors %}
                        <div class="error">{{ form.password.errors }}</div>
                    {% endif %}
                </div>

                <button type="submit" class="btn-login">Register</button>
            </form>
            <div class="form-footer">
                <p>Do you have an account already? <br> <a href="{% url 'users:login' %}">Log in</a></p>
            </div>
        </div>
    </div>
</main>
{% endblock %}