survey_analytics/analysis/urls.py
from django.urls import path

from . import views

app_name = 'analysis'

urlpatterns = [
    path('analysisSurveys/', views.analysisSurveys, name='analysisSurveys'),
    path('lastSurveys/', views.lastSurveys, name='lastSurveys'),
    path('graphs/<int:survey_id>/', views.analysisGraphs, name='analysis_graphs'),
    path('download_pdf/<int:survey_id>/', views.downloadPDF, name='download_pdf'),
    path('delete_survey/<int:survey_id>/', views.deleteSurvey, name='delete_survey'),
]

survey_analytics/survey_analytics/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

handler404 = 'errors.views.handler404'
handler401 = 'errors.views.handler401'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('analysis.urls')),
    path('',include('users.urls')),
    path('',include('errors.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

survey_analytics/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('logout/', views.logout, name='logout'),
    path('forgot-password/', views.PasswordResetView.as_view(), name='password_reset'),
    path('forgot-password/password-reset-done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('change-password/', views.CustomPasswordChangeView.as_view(), name='change_password'),
]

survey_analytics/users/forms.py
# users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.utils.text import capfirst
from django.utils.translation import gettext_lazy as _

# Formulario para el registro de usuarios
class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-input',
            'id': 'password',
            'placeholder': 'Enter your password'
        }),
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-input',
                'placeholder': 'Enter your username'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-input',
                'placeholder': 'Enter your email'
            }),
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email is already in use.")
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        user.is_active = False
        if commit:
            user.save()
        return user


# Formulario para el inicio de sesión
class AuthenticationForm(forms.Form):
    username = forms.CharField(
        max_length=254,
        widget=forms.TextInput(attrs={
            'autofocus': True,
            'class': 'form-input',
            'placeholder': 'Enter your username'
        }),
    )
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={
            'class': 'form-input',
            'placeholder': 'Enter your password',
            'id': 'password',
        }),
    )

    error_messages = {
        'invalid_login': _(
            "Please enter a correct username and password. Note that both fields may be case-sensitive."
        ),
        'inactive': _("This account is inactive. Please activate it"),
    }

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user_cache = None
        super().__init__(*args, **kwargs)
        self.fields['username'].label = capfirst(self.fields['username'].label)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username is not None and password:
            self.user_cache = authenticate(self.request, username=username, password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'username': self.fields['username'].label},
                )
            else:
                self.confirm_login_allowed(self.user_cache)
        return self.cleaned_data

    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

    def get_user(self):
        return self.user_cache

survey_analytics/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout as auth_logout, login as auth_login
from .forms import UserRegisterForm, AuthenticationForm
from .decorators import anonymous_required
from django.utils.decorators import method_decorator
from django.core.mail import EmailMultiAlternatives
from django.conf import settings
from django.template.loader import render_to_string
from django.utils import timezone
from django.urls import reverse, reverse_lazy
from django.contrib.auth.tokens import default_token_generator
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.decorators import login_required

def index(request):
    title = "Homepage"
    return render(request, 'users/index.html', {'title': title})

@anonymous_required(redirect_url='errors:error_400')
def login(request):
    title = "Login"
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            if 'remember_me' in request.POST:
                request.session.set_expiry(1209600)
            else:
                request.session.set_expiry(0)

            context = {
                'user': user,
                'login_datetime': timezone.now().strftime("%d/%m/%Y %H:%M:%S"),
                'device_info': request.META.get('HTTP_USER_AGENT', 'Unknown')
            }

            html_content = render_to_string('emails/login_email.html', context)
            subject = 'Alert: Someone recently logged in'
            from_email = settings.DEFAULT_FROM_EMAIL
            to_email = [user.email]

            msg = EmailMultiAlternatives(subject, '', from_email, to_email)
            msg.attach_alternative(html_content, "text/html")
            msg.send()

            return redirect('users:index')
    else:
        form = AuthenticationForm(request)

    return render(request, 'users/login.html', {'title': title, 'form': form})

@anonymous_required(redirect_url='errors:error_400')
def register(request):
    title = "Register"
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()

            token = default_token_generator.make_token(user)
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            activation_link = request.build_absolute_uri(
                reverse('users:activate', kwargs={'uidb64': uid, 'token': token})
            )

            context = {
                'user': user,
                'activation_link': activation_link,
                'register_datetime': timezone.now().strftime("%d/%m/%Y %H:%M:%S"),
            }

            html_content = render_to_string('emails/register_verification.html', context)
            subject = 'Welcome to our website - Activate your account'
            from_email = settings.DEFAULT_FROM_EMAIL
            to_email = [user.email]
            msg = EmailMultiAlternatives(subject, '', from_email, to_email)
            msg.attach_alternative(html_content, "text/html")
            msg.send()
            messages.info(request,
                          "We have sent you an email to activate your account. Please check your email and activate your account before logging in.")
            return redirect('users:login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'title': title, 'form': form})

def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        User = get_user_model()
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Your account has been successfully activated! You can now log in.')
        return redirect('users:login')
    else:
        messages.error(request, 'The activation link is invalid or has expired.')
        return redirect('users:login')

def logout(request):
    auth_logout(request)
    return redirect('users:index')

@method_decorator(anonymous_required(redirect_url='errors:error_400'), name='dispatch')
class PasswordResetView(auth_views.PasswordResetView):
    template_name = 'users/forgot_password.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    subject_template_name = 'users/password_reset_subject.txt'
    success_url = reverse_lazy('users:password_reset_done')

@method_decorator(anonymous_required(redirect_url='errors:error_400'), name='dispatch')
class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'users/password_reset_done.html'

@method_decorator(anonymous_required(redirect_url='errors:error_400'), name='dispatch')
class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        response = super().form_valid(form)
        auth_logout(self.request)
        messages.success(
            self.request,
            "Your password has been changed and your session has been ended. Please log in again with your new password."
        )
        return response

@method_decorator(login_required(login_url='errors:error_401'), name='dispatch')
class CustomPasswordChangeView(PasswordChangeView):

    template_name = 'users/password_change.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        response = super().form_valid(form)
        auth_logout(self.request)
        messages.success(
            self.request,
            "Your password has been changed successfully. Please log in again."
        )
        return response

survey_analytics/users/templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{{ title }}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
  <script src="{% static 'js/load.js' %}" defer></script>
  <script src="{% static 'js/sidebar.js' %}" defer></script>
  {% block extra_css %}{% endblock %}
  {% block extra_js %}{% endblock %}
</head>
<body>

  <div id="loading-screen">
    <div class="loader"></div>
    <p>Loading...</p>
  </div>

  <header class="header">
    <nav class="navbar">
      <a href="{% url 'users:index' %}" class="logo">SurveyAnalytics</a>

      <button class="menu-toggle" onclick="toggleMenu()">☰</button>

      <ul class="nav-links">
        {% if user.is_authenticated %}
          <li><a href="{% url 'users:index' %}">Home</a></li>
          <li><a href="{% url 'analysis:analysisSurveys' %}">New Surveys</a></li>
          <li><a href="{% url 'analysis:lastSurveys' %}">Last Surveys</a></li>
        {% else %}
          <li><a href="{% url 'users:index' %}">Home</a></li>
        {% endif %}
      </ul>

      {% if user.is_authenticated %}
        <div id="user-info" class="user-info-modal-trigger">
          <img src="{% static 'images/icons/userIcon.svg' %}" alt="User Icon" width="32" height="32">
          <span class="user-name">Hello, {{ user.username }}!</span>
          <div id="user-modal">
            <ul>
              <li><a href="{% url 'users:change_password' %}">Change Password</a></li>
              <li><a href="{% url 'users:logout' %}">Log out</a></li>
            </ul>
          </div>
        </div>
      {% else %}
        <a href="{% url 'users:login' %}" class="nav-button">Log in</a>
      {% endif %}
    </nav>
  </header>

  <div id="sidebar" class="sidebar">
    <button class="close-btn" onclick="toggleMenu()">X</button>
    <h2 class="sidebar-title">Menú de opciones</h2>
    <ul>
      {% if user.is_authenticated %}
        <li class="user-name">Hello, {{ user.username }}!</li>
        <li><a href="{% url 'users:index' %}">Home</a></li>
        <li><a href="{% url 'analysis:analysisSurveys' %}">New Surveys</a></li>
        <li><a href="{% url 'analysis:lastSurveys' %}">Last Surveys</a></li>
      {% else %}
        <li><a href="{% url 'users:index' %}">Home</a></li>
      {% endif %}
      {% if user.is_authenticated %}
        <li><a href="{% url 'users:change_password' %}">Change Password</a></li>
        <li><a href="{% url 'users:logout' %}">Log out</a></li>
      {% else %}
        <li><a href="{% url 'users:login' %}" class="sidebar-login">Log in</a></li>
      {% endif %}
    </ul>
  </div>

  <main class="body">
    {% block content %}{% endblock %}
  </main>

  {% block dropdown_js %}
    <script src="{% static 'js/profileDropdown.js' %}" defer></script>
  {% endblock %}
  {% block below_js %}
  {% endblock %}
</body>
</html>